### PR TITLE
Corrections in width and heigh computation 

### PR DESCRIPTION
**Pull request by nestibal**
Hi,

I've wrote some patch to improve termfair and browse layouts:

Corrections in width and heigh computation ... so as to have true gapless when there some rounding errors

Thanks for your work, it's useful !

### CODE REVIEW

**Comment by vain** [comment]
Thank you! :)

**Comment by nestibal** [comment]
I have also add a new layout based on your one (termfair) and icons similar to those from defalut term for all the layouts if you're intersted ! (yes the week-end was rainy ;-))

**Comment by vain** [comment]
"centerfair" looks interesting. I'll have to play with it for a while to see if it's really useful for me. :)

Okay, now that you created icons for the default theme (nice!), I'll publish mine (zenburn), too. I don't know exactly why I haven't done that before.

Thanks again for your contributions. :)

**Comment by nestibal** [comment]
Hi!

[2012-01-30 09:36:48 -0800] P. Hofmann:

> "centerfair" looks interesting. I'll have to play with it for a while to see if it's really useful for me. :)

Thank! I've coded this one because I have a large screen (1980x1080px)
now and I agree with you about the fact that terminals shouldn't be that
wide. I'll be happy if you like this one too!

> Okay, now that you created icons for the default theme (nice!), I'll publish mine (zenburn), too. I don't know exactly why I haven't done that before.

For the moment I've pushed them in the layout directory but your
organisation is way better I'll pull it!

> Thanks again for your contributions. :)

No problems, I use github for the first time and I love the fact it's
that easy to contribute without to have to be boring with the main
developer! Moreover without your work, it would have been way more
difficult to me to make my layout.

## 

N.

**Pull request merged**
